set -e

echo "*** CREATING TABLE AND GRANTING PRIVILEGES"

mariadb --user=root --password="$MARIADB_ROOT_PASSWORD" --execute \
"CREATE TABLE IF NOT EXISTS test.urls (
    id BIGINT AUTO_INCREMENT, 
    url VARCHAR(4096), 
    length INT, 
    date DATETIME,
    PRIMARY KEY(id)
) ENGINE=InnoDB;

GRANT RELOAD ON *.* TO '$MARIADB_USER'@'%';
GRANT BINLOG MONITOR ON *.* TO '$MARIADB_USER'@'%';
GRANT REPLICATION SLAVE ON *.* TO '$MARIADB_USER'@'%';"

echo "*** TABLE CREATED AND PRIVILEGES GRANTED"
